### ISSUE TITLE
Build will fail until new version is released

### ISSUE THREAD

**Issue by japm48** [hsk81/notex-v2.0#48]
Using `docker build -rm -t hsk81/notex:run .`
Pull request #46 fixes a build error, but the build will still fail because it only uses the last version created (`tag-$(git tag | tail -n1)`).

Please, create a new version (tag) to fix this.

**Comment by hsk81** [comment]
@japm48:
```bash
webed.git $ git push && git push --tags
Everything up-to-date
Total 0 (delta 0), reused 0 (delta 0)
remote: This repository moved. Please use the new location:
remote:   https://github.com/hsk81/notex-v2.0.git
To git@github.com:hsk81/notex.git
 * [new tag]         v2.2.40 -> v2.2.40
```

**Comment by japm48** [comment]
Thanks! Now it works.
