### ISSUE TITLE
Container does not build under debian 8.5 host

### ISSUE THREAD

**Issue by helgein** [hsk81/notex-v2.0#49]
downloads lots of stuff a whole day,
uses git to checkout some source code and crashes at compiling it.

The documentation must be more specific about some reference system:

- what distribution to use as host ?
- what version of docker to use, is 1.11 ok ?
- example stages of the build process.

Right before using debian 8.5, i tried a different VM with debian 7.9 with the backports repo.
I installed the newest kernel from the backports repo to satisfy docker.
The build of the container broke even earlier.

I am unsure if the whole toolchain is still working with nowadays distributions.

**Comment by helgein** [comment]
-rm switch is not recognized anymore. I suppose it should be --rm=true with newer docker.

**Comment by hsk81** [comment]
@helgein: This repository is an *old* version of NoTex (based on `reStructuredText`), which I've *discontinued* (and also stopped supporting). The *current* version of NoTex available at http://notex.ch is `Markdown` based, but I've not (yet) open-sourced it yet.

Therefore, I won't fix this issue; sorry.

**Comment by hsk81** [comment]
@helgein: However, if you really want to use the `reStructuredText` based version of NoTex, then you're welcome to provide a corresponding pull-request, which I'd happily merge into this repository.
